jobs:
  check:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Init
        uses: actions/checkout@v2
      - name: Pull Dependencies
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./check/test

name: Build

on:
  schedule:
    - cron: "25 */6 * * *"
